name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.0
